# Generated by Django 2.2.16 on 2023-03-13 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20230312_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'verbose_name_plural': 'посты',
            },
        ),
    ]
